### ISSUE TITLE
Howto install?

### ISSUE THREAD

**Issue by IamJanS** [majektom/node-red-contrib-satel-integra-integration#1]
Hi,

Great project! How can I make the module available within Node Red?
Thx!

Jan

**Comment by majektom** [comment]
Hi Jan,

I haven't published the module to npm repository yet so you can't install it via "Manage Palette" in the node-red web interface. I will publish it when I have some free time. Hopefully, during this weekend. In the meantime, you can install it with [with npm](https://nodered.org/docs/user-guide/runtime/adding-nodes#installing-with-npm). You have to first checkout the repository and then from within the node-red's user data directory execute:

    npm install </path/to/the/repository>

Hope it was helpful,
Tomasz

**Comment by IamJanS** [comment]
This helps, thank you!
