### ISSUE TITLE
What data should be used in configuration nodes ?

### ISSUE THREAD

**Issue by ilexpl01** [majektom/node-red-contrib-satel-integra-integration#14]
Question regarding:

![image](https://user-images.githubusercontent.com/67930801/150393807-157f2756-8b57-4bc0-b68f-03e902416e75.png)

and

![image](https://user-images.githubusercontent.com/67930801/150393946-6d58b3f8-2bab-4821-8476-f4238a49b540.png)

Can not get that running.

Guideline is pretty sketchy.

BR
M

**Comment by majektom** [comment]
In the user node, you have to insert the code that you normally use in your security system to perform actions requiring user authorization. This is the code that you need to type when you are disarming the system from a manipulator. The "name" field is not important. Insert whatever is meaningful for you to describe the user owning the code.

In the security prefix node, you have to insert the "normal" prefix (not the "duress" prefix) if you did set up code prefixes in your security system. By default, prefixes are turned off in the Integra system. So if you have the prefixes turned off in your system, leave the "prefix" field empty. For more information about the prefixes see paragraph 6.7 of the [Integra programming guide](https://support.satel.pl/download/manual/9953). The "name" field is not important. Insert whatever is meaningful for you.

**Comment by ilexpl01** [comment]
Thx 👍

**Comment by Richardmarobert** [comment]
I would expect an integration key, as the Integra requires this for connection. I cannot find it in the data entry, is that correct?

**Comment by ghost** [comment]
First of all thank you very much! Using your code for more than a year now to read data from my Integra 64. But now I try to write, trying for a day but I don't succeed. I want to change the outputs via functions: 0x88, 0x89. If I understood right: I create a new user in the encoder node.  The "name" is just arbitrary. The "code", that is the code to arm/disarm the system e.g. 9865. I didn't configure a prefix. But what I try I don't get an output to change its state. Do I enter the correct parameters?

**Comment by majektom** [comment]
@Richardmarobert, you probably mean the integration encryption key. This is the key which is used to encrypt the communication between the ETHM-1 module and the client. You can configure it in the `satel-integra-connection` node. See the `Encryption key` field.

**Comment by majektom** [comment]
@IamJanS, yes the name doesn't matter for the communication with the module and the code should be the same that is used to arm/disarm the system. Did you try to base your configuration on [the example](https://github.com/majektom/node-red-contrib-satel-integra-integration#set-output-and-get-its-state) from the README page?

**Comment by ghost** [comment]
Ok, I have to set the output function to "remote switch" duh. It's working now :).

**Comment by Richardmarobert** [comment]
Hi @majektom - I did. I checked if I use the encryption, but it's not set. Despite of that it's not yet coming online. If the parameters are set and the flow is deployed, it should be connecting right away, correct? - haha... and moments later... it is on line :)

**Comment by majektom** [comment]
@Richardmarobert, so I understand that you managed to make it running. Or do you need more help?

**Comment by Richardmarobert** [comment]
@majektom - I did; it works quite well.

**Comment by Richardmarobert** [comment]
@majektom If I would translate the help sentences to Dutch; could you include this in the package?

**Comment by ilexpl01** [comment]
I have installed ethm1 plus card. Enabled integration option. I can not get it running while guardx and dloadx are working fine :/ 

NR flow shows disconnected all the time. I do not use prefixes or encryption. Any hint ? Integra 64 version 1.19.

**Comment by Richardmarobert** [comment]
@ilexpl01 this option enables encryption of the integration . Uncheck it, just use the right port (7094) as integation is available by default from the Integra

**Comment by ilexpl01** [comment]
@Richardmarobert 

I have the encryption option DISABLED & it does not work at all :/

![image](https://github.com/majektom/node-red-contrib-satel-integra-integration/assets/67930801/032c93d6-a189-41bd-b861-12392b44342a)


![image](https://github.com/majektom/node-red-contrib-satel-integra-integration/assets/67930801/60483582-4be4-4dd0-b0e8-ec2febf21a37)

**Comment by ilexpl01** [comment]
Hi to all.

Found the answer to my problem.

I run Domoticz with Satel Integra plugin. It is ON 24/7 and keeps port 7094 busy. all the time 

Once I have for testing purposes disabled the plugin my NR flow started running fine.

Easy ;P
